version: '2'

services:
  db:
    image: postgres:17.6
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    restart: always
    shm_size: '64gb'
    volumes:
      - odoo-db18-data:/var/lib/postgresql/data   # persistent volume

  odoo18:
    image: odoo:18.0
    user: root
    depends_on:
      - db
    ports:
      - "11018:8069"
      - "21018:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo18@2024
    volumes:
      - odoo-web18-data:/var/lib/odoo        # persistent volume (filestore & sessions)
      - ./addons:/mnt/extra-addons           # bind mount for local custom modules
      - ./etc:/etc/odoo                      # bind mount for config/logs
    restart: always
    shm_size: '16gb'

volumes:
  odoo-db18-data:
  odoo-web18-data: